j-rpc:
  server:
    version: 1.0
    port: 8991
    name: forward
  trace:
    more: true
    rate: 0.01
  forward:
    methods:
      forwardTest: test.testMethod
      asyncTest: test.asyncTest
  desensitize:
    settings:
      test: 101



