j-rpc:
  server:
    version: 1.0
    port: 8991
    name: forward
  trace:
    rate: 0.01
  forward:
    methods:
      - { origin: forwardTest, service: test, method: testMethod}
      - { origin: asyncTest, service: test, method: asyncTest}
  desensitize:
    settings:
      test: 101



