j-rpc:
  registry:
    model: zookeeper

    zookeeper:
      address: 127.0.0.1:2181
      namespace: /com.github.jingshouyan.jrpc
  client:
    pool:
      min-idle: 10
      max-idle: 50
      max-total: 200
    connect:
      timeout: 3000


  trace:
    rate: 1.0
    data-show: 2

  desensitize:
    settings:
      name: 11




